name: pokeapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0-14.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.11.0
  floor: ^0.13.0
  retrofit: ^1.3.4
  json_annotation: ^3.0.1
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  cached_network_image: 2.3.0-rc
  auto_route: ^0.6.1
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.11.2
  floor_generator: ^0.13.0
  retrofit_generator: ^1.3.7+2
  json_serializable: ^3.3.0
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/
