name: domain

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  common:
    path: ../common/
  freezed_annotation: ^0.14.1
  injectable: ^1.2.2

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^0.14.1+1
  injectable_generator: ^1.2.2
  lint: ^1.5.3
  mockito: ^5.0.10
  test: ^1.17.8
