// Mocks generated by Mockito 5.3.2 from annotations
// in pokemon_list/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokemon_api/src/pokemon_api.dart' as _i3;
import 'package:pokemon_api/src/requests/get_all_pokemon_request.dart' as _i5;
import 'package:pokemon_api/src/responses/pokemon_list_response.dart' as _i2;
import 'package:shared/data/pokemon_dao.dart' as _i6;
import 'package:shared/data/pokemon_data.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonListResponse_0 extends _i1.SmartFake
    implements _i2.PokemonListResponse {
  _FakePokemonListResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonApi extends _i1.Mock implements _i3.PokemonApi {
  MockPokemonApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PokemonListResponse> getAllPokemons(
          _i5.GetAllPokemonRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPokemons,
          [request],
        ),
        returnValue: _i4.Future<_i2.PokemonListResponse>.value(
            _FakePokemonListResponse_0(
          this,
          Invocation.method(
            #getAllPokemons,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.PokemonListResponse>);
}

/// A class which mocks [PokemonDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonDao extends _i1.Mock implements _i6.PokemonDao {
  MockPokemonDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.PokemonData> getAllPokemons() => (super.noSuchMethod(
        Invocation.method(
          #getAllPokemons,
          [],
        ),
        returnValue: <_i7.PokemonData>[],
      ) as List<_i7.PokemonData>);
  @override
  _i4.Future<_i7.PokemonData?> getPokemonById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPokemonById,
          [id],
        ),
        returnValue: _i4.Future<_i7.PokemonData?>.value(),
      ) as _i4.Future<_i7.PokemonData?>);
  @override
  _i4.Future<void> saveAll(List<_i7.PokemonData>? pokemons) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAll,
          [pokemons],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
