name: pokemon_list
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../../shared

  feature_commons:
    path: ../../libraries/feature_commons

  pokemon_api:
    path: ../../libraries/pokemon_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  bloc_test: ^9.1.0
  mocktail: ^0.3.0



flutter:
  uses-material-design: true
