name: external
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  floor: ^1.1.0
  injectable: ^1.2.2
  json_annotation: ^4.0.1
  retrofit: ^2.0.0

  common:
    path: ../common/
  data:
    path: ../data/

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  floor_generator: ^1.1.0
  injectable_generator: ^1.2.2
  json_serializable: ^4.1.0
  lint: ^1.5.3
  retrofit_generator: ^2.0.0+1
