// Mocks generated by Mockito 5.0.10 from annotations
// in domain/test/usecases/get_all_pokemons_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:domain/core/result.dart' as _i2;
import 'package:domain/entities/pokemon.dart' as _i5;
import 'package:domain/repositories/pokemon_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeResult<T> extends _i1.Fake implements _i2.Result<T> {}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i3.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.Pokemon>>> getAllPokemons() =>
      (super.noSuchMethod(Invocation.method(#getAllPokemons, []),
              returnValue: Future<_i2.Result<List<_i5.Pokemon>>>.value(
                  _FakeResult<List<_i5.Pokemon>>()))
          as _i4.Future<_i2.Result<List<_i5.Pokemon>>>);
}
