name: design_system
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: packages/design_system/fonts/CircularStd-Book.ttf

        - asset: packages/design_system/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: packages/design_system/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: packages/design_system/fonts/CircularStd-Bold.ttf
          weight: 900